import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { ThemeProvider } from '@/context/ThemeContext';
import { Toaster } from "react-hot-toast"
import MySessionProvider from "./_components/mySessionProvider/MySessionProvider";
import CartContextProvider from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <WishlistProvider>
        <CartContextProvider>
        <MySessionProvider>
       <ThemeProvider>
          <div className="mb-18">
          <Navbar  />
          </div>
         
          {children}
          <Toaster />
        </ThemeProvider>

       </MySessionProvider>

        </CartContextProvider>

        </WishlistProvider>
        
      
       
      </body>
    </html>
  );
}
